AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lead-emails-processor

  Sample SAM Template for lead-emails-processor
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LeadEmailProcessor:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./build.zip
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        RespageLeadEmailsTrigger:
          Type: S3 # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3
          Properties:
            Bucket:
              Ref: RespageLeadEmails
            Events: s3:ObjectCreated:*

  RespageLeadEmails:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: respage-lead-emails

Outputs:
  LeadEmailProcessor:
    Description: "LeadEmailProcessor Lambda Function ARN"
    Value: !GetAtt LeadEmailProcessor.Arn
  LeadEmailProcessorIamRole:
    Description: "Implicit IAM Role created for LeadEmailProcessor function"
    Value: !GetAtt LeadEmailProcessorRole.Arn
